/************************************************************************************************************
@author         Echo : Swati Mathur
@date           28 Mar 2018
@description:   This is the constants class for all static strings used in this namespace
**************************************************************************************************************/
public class FcUt_Constants {

    // Get the prefix and append it to the object and fields API names
    private static String NAMESPACEPREFIX = GlUt_NamespacePrefix.getNamespacePrefix();
    //The prefix for this namespace
    public static string PREFIX = 'FcUt_';
    public static string ID = 'Id';
    // Constans for FcUt_CentralDispatcher
    public static String PENDING              = 'Pending' ;
    public static String BILLITEM             = 'Bill Item';
    public static String MONTH                = 'Month' ;
    public static String AMENDMENT            = 'Amendment';
    public static String PAYMENT              = 'Payment';
    public static String GOODWILL             = 'Goodwill';
    public static String RETURNTRANSFER       = 'Return/Transfer';
    public static String REFUND               = 'Refund';
    public static String PAYALLOC             = 'Payment Allocation';
}