public class GlUt_APIConstantsRuralGrossConsumption {
    
    // Get the prefix and append it to the object and fields api names
    private static String NAMESPACEPREFIX = GlUt_NamespacePrefix.getNamespacePrefix();
    
    // Rural Gross Consumption Object API Name
    public static String  RURALGROSSCONSUMPTIONAPINAME = NAMESPACEPREFIX + 'RuralGrossConsumption__c';
    
    public static String  TYPEAPINAME = NAMESPACEPREFIX + 'Type__c'; 
    public static String  RURALENTITLEMENTAPINAME = NAMESPACEPREFIX + 'RuralEntitlement__c';   
    
}