public class GlUt_APIConstantsDirectDebitReturn {
    // Get the prefix and append it to the object and fields api names
    private static String NAMESPACEPREFIX = GlUt_NamespacePrefix.getNamespacePrefix();
    
    // Bank Account Change Object API Name
    public static String  DIRECTDEBITRETURNAPINAME = NAMESPACEPREFIX + 'DirectDebitReturn__c';
    
    // Bank Account Change object fields API Names
    public static String  STATUSAPINAME = NAMESPACEPREFIX + 'Status__c';
    
}