/************************************************************************************************************
@author         ECHO : Mohit Tayal
@date           04-Jun-2018
@description:   This is the constants class for all static strings used in this namespace
**************************************************************************************************************/
public class LtBt_Constants {

    // The prefix for this namespace
    public static string NAMESPACEPREFIX = GlUt_NamespacePrefix.getNamespacePrefix();
    
    public static string PREFIX          = 'LtUt_';
    
    public static String XMLENCODING            = 'UTF-8';
    public static String PDFREQUESTSTAG         = 'PDFRequests';
    public static String FILENAMECORRESPONDENCE = 'Correspondence';
    public static String DATETIMEFORMAT         = 'yyyy-mm-dd_hh-mm-ss';
    public static String XMLFILEEXTENSION       = '.xml';
    public static String COMPLETEDPDFSTATUS     = 'Completed';
    public static String PENDINGPDFSTATUS       = 'Pending';
    public static String HTMLPDFSOURCETYPE      = 'HTML';
    public static String PDFREQUESTTAG          = 'PDFRequest';
    public static String SOURCETYPETAG          = 'SourceType';
    public static String ACCOUNTTAG             = 'Account_Id';
    public static String CONTRACTTAG            = 'Contract_Id';
    public static String CONTACTTAG             = 'Contact_Id';
    public static String HTMLBODYTAG            = 'HtmlBody';
}